version: "3"

services:
  frontend:
    environment:
      VITE_BACKEND_URL: http://localhost:8001
    build:
      context: ./frontend/app/
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/app:/app:delegated
      - /app/node_modules
    ports:
      - "8000:5173"

  api-gateway:
    build:
      context: ./backend/api-gateway/app/
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/api-gateway/app:/app:delegated
      - /app/node_modules
    ports:
      - "8001:80"
