config:
  aws:region: ap-southeast-1
  question-service-infra:MONGO_ATLAS_DB_NAME: "questions_db"
  question-service-infra:MONGO_ATLAS_PASSWORD:
    secure: AAABAM/hNcOqzbPSws/d0m4kNehiS5LBnjZbsTUga4B32WflgvMvnA==
  question-service-infra:MONGO_ATLAS_USERNAME:
    secure: AAABAHjd/PPgD4Y6HG0z/3JobRAap84bGNmw+c/wNQm/9HEFpA==
  question-service-infra:MONGODB_ATLAS_ORG_ID:
    secure: AAABAAIpZXmh9dk844iWEW4jbg8MTQb7/knUOH8u4X8bqi/d2zK6ulGSwOFuTtFBBI88n9tODb0=
  question-service-infra:MONGODB_ATLAS_PRIVATE_KEY:
    secure: AAABAJCTbzjLGvFRsYm8S1OqOcwD2BJxm1eXwC7YzOaLMELGUTBFI9ndn02eonc+Hh7D8/Nb3VRuFXlNYyeSxNYuu6k=
  question-service-infra:MONGODB_ATLAS_PUBLIC_KEY:
    secure: AAABAEhImQJ3fWhr/Zb0rIGm2BdgtcrWQzVUyv2qysu1EIL+BDxdEQ==
  question-service-infra:acmEcsCertificateArn:
    secure: AAABAEPKI63kQJV4DYXAg1juSMmE+BzreNtOTVU1NBnf6XZJtZ53Hs64thD1gIS+6kZEbPdjppxSRBkxSOu+AwGwb3rgpOWgI5lqjMWPR8r6/LG5PAJ/7rG9h0BpT5vzkwAi/q+mjox25DQVBSE5/u9OM8m7zOk6
  question-service-infra:apiGatewayAuthSecret:
    secure: AAABAAa7juyAoGUHGV+/FnarVuyAEUqhpodBtPnbO3K+H7xXG0OutFJW57W9yRY/ATriui3gIW3BaBY89bIXJ1ZglEErixNtFxCL8SfKMa2ljSbo+Liglu+iBKYVpxx6qGyU1lGwoqABiyiy8xv+kpI0TuaF1BL97e9UWkDK35KsxHx3lE7H0SQZWxbtPyKWU8/eXNHqa31tFSsiO/Mm/LxVMKQd82gfUdDipUDumAxCfzMh+fuEsUlmrfUNaYjT
  question-service-infra:hostedZoneId:
    secure: AAABAHIleSxYEMghB30hmWedm0BN7TjJ9YQtKb5uo8oKC8xUsauoe3qhZtyshddizh+Fmw==
  question-service-infra:rootDomain: peerprep.net
  question-service-infra:subdomain: questions.
  question-service:containerPort: "80"
  question-service:cpu: "512"
  question-service:memory: "128"
