config:
  aws:region: ap-southeast-1
  user-service-infra:DATABASE_URL:
    secure: AAABAOVb2p75vguLgK2Ylo0Tc92yC38HOthiXS8WYSRRi/lv0LJ17xQZtMPFP4gnI/j0XJ7Xtv8yuuia7UP+GVOjJGEV1nsWx3tGxE2HHUwHdxE8nV7dDH6t1MQWkQ6ImrK948nT8Shep+EvQ/e4Y+OpPg3PjjrkomZfTCNK7Bp+bUXls7tnXQ+7GE9hvoszutl1MRmZ2w2jnXluQK/N
  user-service-infra:acmEcsCertificateArn:
    secure: AAABABfVPz1lrxMIq0tHzvKSuWtgOfu2uUxyd0qP4uz0jS7PJjdMgBZIyGsSNywoi97kCh/L15W+sxpQPBOlmCWW0I40xxfYzUDIIkL30gJwoZSAzanNSBN8ii2dw3yCRrDnrDeC9xTxp3QteO4RPB+z6cZqzaXc
  user-service-infra:apiGatewayAuthSecret:
    secure: AAABALE+SH/FwVzVxxXP1gABIp5/fNUktl+UvZyXsrVrmyD5H1qtwcFvWZPk2korFz4QBUDdm64lS/V09dpm5nQJpXzJ/UGitf+rXTAq8z5v/vsTH1HYUkzMDaWrvPECjaoQR9jRZUn9lsH1bH8Gr1YnEQKiLPNq2jX7DDnIzOxOS/c8L6Eo+65o9tsANboS4/LiPuM6jRJf2CSUy8ccSVWdSmrYI6BwJ9J6Wo4leSsJjotJymL+/kE7qbH/nMjR
  user-service-infra:containerPort: "80"
  user-service-infra:cpu: "256"
  user-service-infra:hostedZoneId:
    secure: AAABAHSwRJHb5rGPJk6+3XTvT5pBJcbaTs/2tUBTlL4+JsPts/ZYJdw1yueSp/ccPjKRTA==
  # user-service-infra:hostedZoneId:
  #   secure: AAABAPo+L6MruYRAe+3DrUVHDytqg9h7GMUj0ofzzxPBoBc6P1/FCfs4kS6qE7K6EqJ0lA==
  user-service-infra:memory: "128"
  user-service-infra:path: ../app
  user-service-infra:rootDomain: peerprep.net
  user-service-infra:subdomain: users.
